# Generated by Django 5.2.3 on 2025-06-23 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='join_code',
            field=models.CharField(default='81B8497311', max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='SocialToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=30)),
                ('uid', models.CharField(max_length=100, unique=True)),
                ('access_token', models.TextField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_token', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
