# Generated by Django 5.2.3 on 2025-06-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_alter_socialaccount_user_alter_team_join_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='game',
            field=models.CharField(choices=[('BATTLEFIELD', 'Battlefield'), ('NHL', 'NHL'), ('OTHER', 'Other')], default='BATTLEFIELD', max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='join_code',
            field=models.CharField(default='922C0F700D', max_length=10, unique=True),
        ),
    ]
