# Generated by Django 5.2.3 on 2025-06-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_alter_team_join_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='join_code',
            field=models.CharField(default='B6ED2CEE8C', max_length=10, unique=True),
        ),
    ]
